### ISSUE TITLE
Commands Would Be Better Off Closer To Other 'Open' Context Menu Commands

### ISSUE THREAD

**Issue by yannduran** [Therena/OpenFolderExtension#1]
First off, I love your extension! 🥇

However the positioning of your context menu commands seem a little bit 'random' (don't worry, other extension authors do it as well, including Microsoft sometimes). Your commands might be found a little bit easier if they were close to other commands that start with 'Open'.

If you're not sure what I mean, I could give you more specific examples, but I'm expecting that you'll know what I mean now that I've mentioned it.

**Comment by Therena** [comment]
> First off, I love your extension! 🥇

Thank you :)
And sorry for the late answer to this issue.

> Your commands might be found a little bit easier if they were close to other commands that start with 'Open'.

I understand what you mean, but it is quite hard to be always a the same position.
Each further extension could move in between.

Anyway I will see what I could do to make the positioning better.

**Comment by yannduran** [comment]
That's great! Thanks for listening.

To be a little clearer, I was mainly referring to the project context menu, where there is already a built-in _Open in Windows Explorer_ command  (I think it's part of VS now). To me, that seems like the perfect place for your commands to go as well.

Actually if the command I mentioned is in fact built-in now, you may not need one of your commands anymore. But the _Open Output Path_ command is great!

**Comment by Therena** [comment]
The position of the context menu item got changed with the latest release 1.2019.0.2
