### ISSUE TITLE
Folders are not open in command line if used another drive

### ISSUE THREAD

**Issue by rorsulak** [Therena/OpenFolderExtension#2]
Folders are not open in command line because folder is on another drive.
E.g. output folder is on D: drive, but command line opens on C: drive
If I write in command line D: path is correct.

**Comment by Therena** [comment]
Hey @rorsulak thanks for reporting this bug.
I just uploaded a new version of the extension (1.2019.0.3) there it should be fix.

Could you please check if it works for you?

**Comment by rorsulak** [comment]
Thank you for fast fix. Now it works fine.
Very good extension. Thank you
