### ISSUE TITLE
Folder is not open in powershell if it ends with backslash

### ISSUE THREAD

**Issue by rorsulak** [Therena/OpenFolderExtension#3]
If folder ends with backslash (e.g. output folder) powershell is open, but with error:
```powershell
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```

**Comment by Therena** [comment]
Hey @rorsulak thanks for reporting this bug.
I just uploaded a new version of the extension (1.2019.0.3) there it should be fix.

Could you please check if it works for you?

**Comment by rorsulak** [comment]
Thank you for fast fix. Now it works fine.
Very good extension. Thank you
