### ISSUE TITLE
Focus file in the explorer while opening the path

### ISSUE THREAD

**Issue by Therena** [Therena/OpenFolderExtension#4]
While opening the folder also the files should be selected

**Comment by Therena** [comment]
Looks like there is a option by using the "/select" parameter of the explorer.
Going to see how I can integrate this in a proper way.

**Comment by AdmiralSnyder** [comment]
https://web.archive.org/web/20150602220856/https://support.microsoft.com/en-us/kb/152457

explorer /select,c:\temp\myfile.xml
opens c:\temp folder, with myfile.xml selected

**Comment by Therena** [comment]
Please have a look on 1.2019.0.4
It has this feature included.
Thanks for the idea.
