### ISSUE TITLE
Error when opening folder with space in powershell

### ISSUE THREAD

**Issue by rorsulak** [Therena/OpenFolderExtension#5]
Hi,
If you try to open folder in powershell and folder contains space(s), powershell is open with error:
`Set-Location : A positional parameter cannot be found that accepts argument ...`

For opening folder in command line and in file explorer it works correctly with spaces.

**Comment by Therena** [comment]
Hey @rorsulak thanks for reporting this bug.
I just uploaded a new version of the extension (1.2019.0.4) there it should be fix.

Could you please check if it works for you?

**Comment by rorsulak** [comment]
Hi,
Now it works fine.
Thank you for fast fix.
